version: '3'
services:
  kicker-config:
    image: n52/kicker-config:latest
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        JAR_FILE: "build/libs/kicker-config-server-0.0.1-SNAPSHOT.jar"
    volumes: 
      - ./persistence/tmp:/tmp
    ports: 
      - 8888:8888
