server:
  port: 8888
spring:
  application: 
    name: kicker-config-server
  config:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
